-- MySQL Script generated by MySQL Workbench
-- Tue Apr 18 18:02:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_pedro_segundo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_pedro_segundo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_pedro_segundo` DEFAULT CHARACTER SET utf8 ;
USE `hospital_pedro_segundo` ;

-- -----------------------------------------------------
-- Table `hospital_pedro_segundo`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_pedro_segundo`.`Consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `médico` VARCHAR(45) NOT NULL COMMENT 'Médico responsável pela consulta.',
  `especialidade_med` VARCHAR(45) NOT NULL COMMENT 'Especialidade do médico ( buscada anteriormente pelo paciente )',
  `valorconsulta` VARCHAR(45) NOT NULL COMMENT 'Valor da consulta.',
  `data da consulta` VARCHAR(45) NOT NULL,
  `número da carteira` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_pedro_segundo`.`Convênio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_pedro_segundo`.`Convênio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL COMMENT 'Nome do convênio.',
  `CNPJ` VARCHAR(45) NULL COMMENT 'CNPJ do Convênio.',
  `tempo de carência` VARCHAR(45) NULL COMMENT 'Tempo de carência do Convênio.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_pedro_segundo`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_pedro_segundo`.`Pacientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT 'Nome do paciente.',
  `consulta` VARCHAR(45) NOT NULL COMMENT 'Consulta do paciente.',
  `CPF` VARCHAR(45) NOT NULL COMMENT 'Cadastro de Pessoa Física ( Informação Pessoal )',
  `RG` VARCHAR(45) NOT NULL COMMENT 'Registro Geral ( Informação Pessoal )',
  `data de nascimento` VARCHAR(45) NOT NULL COMMENT 'Data de aniversário do paciente.',
  `telefone` VARCHAR(45) NOT NULL COMMENT 'Telefone do paciente.',
  `endereço de email` VARCHAR(45) NOT NULL COMMENT 'Endereço de email do paciente.',
  `endereço` VARCHAR(200) NOT NULL,
  `convênio` VARCHAR(45) NULL COMMENT 'Convênio do paciente ( Se houver ou não ).',
  PRIMARY KEY (`id`),
  INDEX `fk_Pacientes_Consulta1_idx` (`consulta` ASC) VISIBLE,
  INDEX `fk_Pacientes_Convênio1_idx` (`convênio` ASC) VISIBLE,
  CONSTRAINT `fk_Pacientes_Consulta1`
    FOREIGN KEY (`consulta`)
    REFERENCES `hospital_pedro_segundo`.`Consulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacientes_Convênio1`
    FOREIGN KEY (`convênio`)
    REFERENCES `hospital_pedro_segundo`.`Convênio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_pedro_segundo`.`Médicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_pedro_segundo`.`Médicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL COMMENT 'Nome do médico',
  `especialidade` VARCHAR(45) NOT NULL COMMENT 'Especialidade do médico.',
  `pacientes` VARCHAR(45) NOT NULL COMMENT 'Pacientes que o médico possui.',
  `pediatria` VARCHAR(45) NOT NULL COMMENT 'Se ele for da área de pediatria',
  `clínico geral` VARCHAR(45) NOT NULL COMMENT 'Se ele for da área de Clínico Geral',
  `gastroenterologia` VARCHAR(45) NOT NULL COMMENT 'Se ele for da área de gastroenterologia',
  `dermatologista` VARCHAR(45) NOT NULL COMMENT 'Se ele for da área de dermatologia',
  `receitas` VARCHAR(45) NULL COMMENT 'Receitas do médico indicadas anteriormente.',
  PRIMARY KEY (`id`),
  INDEX `fk_Médicos_Pacientes1_idx` (`pacientes` ASC) VISIBLE,
  CONSTRAINT `fk_Médicos_Pacientes1`
    FOREIGN KEY (`pacientes`)
    REFERENCES `hospital_pedro_segundo`.`Pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_pedro_segundo`.`Hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_pedro_segundo`.`Hospital` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `médicos` VARCHAR(45) NOT NULL COMMENT 'Médicos do hospital.',
  `pacientes` VARCHAR(45) NOT NULL COMMENT 'Pacientes do hospital.',
  `consulta` VARCHAR(45) NOT NULL COMMENT 'Consulta do hospital.',
  PRIMARY KEY (`id`),
  INDEX `fk_Hospital_Médicos_idx` (`médicos` ASC) VISIBLE,
  INDEX `fk_Hospital_Pacientes1_idx` (`pacientes` ASC) VISIBLE,
  INDEX `fk_Hospital_Consulta1_idx` (`consulta` ASC) VISIBLE,
  CONSTRAINT `fk_Hospital_Médicos`
    FOREIGN KEY (`médicos`)
    REFERENCES `hospital_pedro_segundo`.`Médicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_Pacientes1`
    FOREIGN KEY (`pacientes`)
    REFERENCES `hospital_pedro_segundo`.`Pacientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hospital_Consulta1`
    FOREIGN KEY (`consulta`)
    REFERENCES `hospital_pedro_segundo`.`Consulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_pedro_segundo`.`Receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_pedro_segundo`.`Receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medicamentos` VARCHAR(45) NOT NULL COMMENT 'Tipo do medicamento.',
  `qnt_medicamentos` VARCHAR(45) NOT NULL COMMENT 'Quantidade de medicamentos.',
  `inst_medicamentos` VARCHAR(45) NOT NULL COMMENT 'Instruções de medicamentos.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
