-- MySQL Script generated by MySQL Workbench
-- Fri Apr 21 22:52:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_otavio_alves
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_otavio_alves
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_otavio_alves` DEFAULT CHARACTER SET utf8 ;
USE `hospital_otavio_alves` ;

-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Convenio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(40) NOT NULL,
  `tempo_carencia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Convenio_id` INT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Paciente_Convenio1_idx` (`Convenio_id` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Convenio1`
    FOREIGN KEY (`Convenio_id`)
    REFERENCES `hospital_otavio_alves`.`Convenio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Especialidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Consulta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `especialidade_id` INT NOT NULL,
  `convenio_id` INT NOT NULL,
  `data_hora_realizacao` DATETIME NOT NULL,
  `valor_consulta` DECIMAL(3,2) NOT NULL,
  `numero_carteira` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `paciente_id`, `medico_id`, `especialidade_id`),
  INDEX `fk_Consulta_Paciente1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_Consulta_Medico1_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_Consulta_Especialidade1_idx` (`especialidade_id` ASC) VISIBLE,
  INDEX `fk_Consulta_Convenio1_idx` (`convenio_id` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_otavio_alves`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Medico1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `hospital_otavio_alves`.`Medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Especialidade1`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `hospital_otavio_alves`.`Especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Convenio1`
    FOREIGN KEY (`convenio_id`)
    REFERENCES `hospital_otavio_alves`.`Convenio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Receita` (
  `consulta_id` INT NOT NULL,
  `receita_escrita` TEXT NULL COMMENT 'Medicamentos receitados, a quantidade de medicamentos receitados e as instruções de uso dos tais.',
  UNIQUE INDEX `Consulta_id_UNIQUE` (`consulta_id` ASC),
  CONSTRAINT `fk_Receita_Consulta`
    FOREIGN KEY (`consulta_id`)
    REFERENCES `hospital_otavio_alves`.`Consulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Medico_Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Medico_Especialidade` (
  `medico_id` INT NOT NULL,
  `especialidade_id` INT NOT NULL,
  PRIMARY KEY (`medico_id`, `especialidade_id`),
  INDEX `fk_Medico_Especialidade_Especialidade1_idx` (`especialidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Especialidade_Medico1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `hospital_otavio_alves`.`Medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medico_Especialidade_Especialidade1`
    FOREIGN KEY (`especialidade_id`)
    REFERENCES `hospital_otavio_alves`.`Especialidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Enfermeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Enfermeiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cpf` CHAR(9) NOT NULL,
  `cre` CHAR(9) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Tipo_quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Tipo_quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `valor_diaria` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Quarto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Quarto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(200) NOT NULL,
  `tipo_quarto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_quarto_id`),
  INDEX `fk_Quarto_Tipo_quarto1_idx` (`tipo_quarto_id` ASC) VISIBLE,
  CONSTRAINT `fk_Quarto_Tipo_quarto1`
    FOREIGN KEY (`tipo_quarto_id`)
    REFERENCES `hospital_otavio_alves`.`Tipo_quarto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Internacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Internacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_entrada` DATETIME NOT NULL,
  `data_prev_alta` DATETIME NOT NULL,
  `data_alta` DATETIME NOT NULL,
  `procedimento` TEXT NOT NULL,
  `paciente_id` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `quarto_id` INT NOT NULL,
  PRIMARY KEY (`id`, `paciente_id`, `medico_id`, `quarto_id`),
  INDEX `fk_Internacao_Paciente1_idx` (`paciente_id` ASC) VISIBLE,
  INDEX `fk_Internacao_Medico1_idx` (`medico_id` ASC) VISIBLE,
  INDEX `fk_Internacao_Quarto1_idx` (`quarto_id` ASC) VISIBLE,
  CONSTRAINT `fk_Internacao_Paciente1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `hospital_otavio_alves`.`Paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Internacao_Medico1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `hospital_otavio_alves`.`Medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Internacao_Quarto1`
    FOREIGN KEY (`quarto_id`)
    REFERENCES `hospital_otavio_alves`.`Quarto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_otavio_alves`.`Internacao_Enfermeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_otavio_alves`.`Internacao_Enfermeiro` (
  `internacao_id` INT NOT NULL,
  `enfermeiro_id` INT NOT NULL,
  PRIMARY KEY (`internacao_id`, `enfermeiro_id`),
  INDEX `fk_Internacao_has_Enfermeiro_Enfermeiro1_idx` (`enfermeiro_id` ASC) VISIBLE,
  INDEX `fk_Internacao_has_Enfermeiro_Internacao1_idx` (`internacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Internacao_has_Enfermeiro_Internacao1`
    FOREIGN KEY (`internacao_id`)
    REFERENCES `hospital_otavio_alves`.`Internacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Internacao_has_Enfermeiro_Enfermeiro1`
    FOREIGN KEY (`enfermeiro_id`)
    REFERENCES `hospital_otavio_alves`.`Enfermeiro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
